"""ClipForge Stage A — analysis bundle assembly (ARCHITECTURE.md §7.2).

Assembles the release-ready analysis bundle for a job after ingest +
transcribe + scenes have run:

  * ``00_READ_THIS_FIRST.txt`` — generated by ``pipeline/plan/prompt.py``
    (the wording is part of the contract; change it deliberately).
  * ``screenshots.zip``        — baseline ``frame_*.jpg`` 6-second composites.
  * ``event_composites.zip``   — dense ``event_*.jpg`` composites (optional;
    also duplicated inside ``screenshots.zip`` so the legacy prompt wording —
    "two kinds of image live inside" — stays literally true).
  * ``manifest.json``          — machine-readable index per
    ``schemas/analysis_bundle.schema.json`` (name, purpose, size, sha256).

The bundle directory also receives contract-named copies of the pipeline
outputs the workflow produced: ``source_input.bin`` (original quality),
``transcript.json``, ``scene_index.json``, ``key_moments.json``.
(``analysis_720p.mp4`` was removed from the bundle by bug-68: nothing
downstream ever read it, so it is no longer transcoded, bundled, or
uploaded.) Asset download URLs are filled into the manifest by the
workflow after the release is created (the ``url`` field is optional in the
schema and left empty here).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
import zipfile
from pathlib import Path
from typing import Any, Callable

from .ingest import load_request

# (filename, purpose, optional) — purposes are the enums in
# schemas/analysis_bundle.schema.json. Order is the release listing order.
BUNDLE_ASSETS: list[tuple[str, str, bool]] = [
    ("source_input.bin", "source_full_quality", False),
    ("transcript.json", "transcript", False),
    ("screenshots.zip", "baseline_composites", False),
    ("event_composites.zip", "dense_event_composites", True),
    ("scene_index.json", "shot_boundaries", False),
    ("key_moments.json", "key_moments", False),
    ("00_READ_THIS_FIRST.txt", "agent_prompt", False),
    ("manifest.json", "self_manifest", False),
]


class BundleError(RuntimeError):
    """A bundle-assembly failure (missing inputs, prompt failure)."""


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def make_zip(src_dir: Path, dest: Path, predicate: Callable[[str], bool]) -> int:
    """Zip every file in ``src_dir`` whose name passes ``predicate``.

    Stored (not re-deflated) since the JPEGs are already compressed. Returns
    the number of files packed.
    """
    names = sorted(p.name for p in src_dir.iterdir() if p.is_file() and predicate(p.name))
    if not names:
        return 0
    dest.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(dest, "w", compression=zipfile.ZIP_STORED) as zf:
        for name in names:
            zf.write(src_dir / name, arcname=name)
    return len(names)


def generate_prompt(
    job_id: str,
    request: dict[str, Any],
    work_dir: Path,
    *,
    duration_seconds: int,
    baseline_count: int,
    window_seconds: int,
    shot_count: int,
    key_moment_count: int,
    event_frame_count: int,
) -> Path:
    """Generate ``00_READ_THIS_FIRST.txt`` via pipeline.plan.prompt.

    Free-form user text (focus, series context) is passed through the
    environment, never through argv, exactly as the legacy workflow did.
    """
    options = request.get("options") or {}
    series = request.get("series") or {}
    target = int(options.get("target_duration_seconds", 120) or 120)
    if target <= 0:
        target = 120

    out_path = work_dir / "00_READ_THIS_FIRST.txt"
    env = dict(os.environ)
    env["CLIPFORGE_FOCUS"] = str(options.get("focus", "") or "")
    env["CLIPFORGE_SERIES_CONTEXT"] = str(series.get("context", "") or "")

    cmd = [
        sys.executable, "-m", "pipeline.plan.prompt",
        str(int(duration_seconds)), str(int(baseline_count)), str(out_path),
        "--target-duration", str(target),
        "--job-id", job_id,
        "--window-seconds", str(int(window_seconds)),
        "--shot-count", str(int(shot_count)),
        "--key-moment-count", str(int(key_moment_count)),
        "--event-frame-count", str(int(event_frame_count)),
        "--focus-env", "CLIPFORGE_FOCUS",
    ]
    if series.get("enabled"):
        part = int(series.get("part", 0) or 0)
        start = int(series.get("start_seconds", 0) or 0)
        if part < 1 or start < 0:
            raise BundleError("series prompts require a positive part and non-negative start")
        cmd += [
            "--series-part", str(part),
            "--series-start-seconds", str(start),
            "--series-id", str(series.get("series_id") or ""),
            "--series-context-env", "CLIPFORGE_SERIES_CONTEXT",
        ]

    proc = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if proc.returncode != 0:
        print(proc.stdout[-2000:], file=sys.stderr)
        print(proc.stderr[-2000:], file=sys.stderr)
        raise BundleError(f"prompt generation failed (exit {proc.returncode})")
    print(proc.stdout.strip(), flush=True)
    if not out_path.is_file() or out_path.stat().st_size == 0:
        raise BundleError("prompt generation produced no output file")
    return out_path


def _read_count(path: Path, key: str) -> int:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return int(data.get(key, 0) or 0)
    except (OSError, json.JSONDecodeError, ValueError):
        return 0


def run_bundle(
    job_id: str,
    work_dir: str,
    release_tag: str,
    *,
    jobs_root: str = "jobs",
    duration_seconds: int | None = None,
    window_seconds: int = 6,
) -> dict[str, Any]:
    """Assemble the full bundle under ``<work_dir>/bundle`` and return the
    manifest dict (also written to ``<work_dir>/bundle/manifest.json``)."""
    work = Path(work_dir)
    bundle_dir = work / "bundle"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    request = load_request(job_id, root=jobs_root)

    # ---- locate pipeline outputs -------------------------------------------
    ingest_record_path = Path(jobs_root) / job_id / "ingest.json"
    original_path: Path | None = None
    if ingest_record_path.is_file():
        try:
            original_path = Path(json.loads(
                ingest_record_path.read_text(encoding="utf-8")).get("original_path", ""))
        except json.JSONDecodeError:
            original_path = None
    if original_path is None or not original_path.is_file():
        # Series continuations reuse the source job's evidence; the workflow
        # stashes the original at work/original.<ext>.
        originals = sorted(work.glob("original.*"))
        if originals:
            original_path = originals[0]
    if original_path is None or not original_path.is_file():
        raise BundleError("no original source video found for the bundle")

    # bug-68: the 720p analysis copy is no longer required, bundled, or even
    # produced — nothing downstream ever consumed it.
    transcript_json = work / "transcript.json"
    scene_index_json = work / "scene_index.json"
    key_moments_json = work / "key_moments.json"
    for required in (transcript_json, scene_index_json, key_moments_json):
        if not required.is_file():
            raise BundleError(f"missing required Stage A output: {required}")

    # ---- stats --------------------------------------------------------------
    screenshots_dir = work / "screenshots"
    baseline_count = 0
    event_count = 0
    if screenshots_dir.is_dir():
        baseline_count = sum(1 for p in screenshots_dir.iterdir() if p.name.startswith("frame_"))
        event_count = sum(1 for p in screenshots_dir.iterdir() if p.name.startswith("event_"))

    if duration_seconds is None:
        try:
            tx = json.loads(transcript_json.read_text(encoding="utf-8"))
            duration_seconds = int(round(float(tx.get("audio_duration_seconds") or 0)))
        except (OSError, json.JSONDecodeError, ValueError):
            duration_seconds = 0
        if duration_seconds <= 0:
            duration_seconds = _read_count(scene_index_json, "video_duration_seconds") or None
        if not duration_seconds:
            raise BundleError("could not determine source duration for the prompt")
    duration_seconds = int(duration_seconds)

    shot_count = _read_count(scene_index_json, "shot_count")
    key_moment_count = _read_count(key_moments_json, "moment_count")

    # ---- prompt --------------------------------------------------------------
    prompt_path = generate_prompt(
        job_id, request, work,
        duration_seconds=duration_seconds,
        baseline_count=baseline_count,
        window_seconds=window_seconds,
        shot_count=shot_count,
        key_moment_count=key_moment_count,
        event_frame_count=event_count,
    )

    # ---- zips ------------------------------------------------------------------
    # screenshots.zip keeps BOTH kinds inside (the legacy prompt wording —
    # part of the contract — says so). event_composites.zip is the §7.2
    # dense-only view, emitted only when event composites exist.
    if screenshots_dir.is_dir():
        packed = make_zip(screenshots_dir, work / "screenshots.zip",
                          lambda n: n.startswith(("frame_", "event_")))
        if packed == 0:
            raise BundleError("no screenshot composites found to pack")
        if event_count:
            make_zip(screenshots_dir, work / "event_composites.zip",
                     lambda n: n.startswith("event_"))
    else:
        raise BundleError(f"screenshots directory missing: {screenshots_dir}")

    # ---- stage contract-named copies ------------------------------------------
    staged: dict[str, Path] = {
        "source_input.bin": original_path,
        "transcript.json": transcript_json,
        "scene_index.json": scene_index_json,
        "key_moments_json".replace("_json", ".json"): key_moments_json,
        "00_READ_THIS_FIRST.txt": prompt_path,
        "screenshots.zip": work / "screenshots.zip",
    }
    event_zip = work / "event_composites.zip"
    if event_zip.is_file():
        staged["event_composites.zip"] = event_zip

    for name, src in staged.items():
        shutil.copyfile(src, bundle_dir / name)

    # ---- manifest ---------------------------------------------------------------
    manifest = build_manifest(job_id, release_tag, bundle_dir)
    (bundle_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote manifest to {bundle_dir / 'manifest.json'} "
          f"({len(manifest['assets'])} assets)", flush=True)
    return manifest


def build_manifest(job_id: str, release_tag: str, bundle_dir: Path) -> dict[str, Any]:
    """Build the §7.2 manifest from the files actually present in bundle_dir.

    ``manifest.json``'s own entry (purpose ``self_manifest``) carries no
    size/sha — it cannot hash itself; both fields are optional in the schema.
    ``url`` is left empty; the workflow fills it after the release exists.
    """
    assets: list[dict[str, Any]] = []
    for name, purpose, optional in BUNDLE_ASSETS:
        path = bundle_dir / name
        if name == "manifest.json":
            assets.append({"name": name, "purpose": purpose, "optional": True})
            continue
        if not path.is_file():
            if optional:
                continue
            raise BundleError(f"required bundle asset missing: {name}")
        assets.append({
            "name": name,
            "purpose": purpose,
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path),
            **({"optional": True} if optional else {}),
        })
    if not any(a["name"] == "00_READ_THIS_FIRST.txt" for a in assets):
        raise BundleError("bundle is missing its agent prompt")
    return {
        "version": 1,
        "job_id": job_id,
        "release_tag": release_tag,
        "created_at_epoch": int(time.time()),
        "assets": assets,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="ClipForge Stage A bundle assembly")
    ap.add_argument("job_id")
    ap.add_argument("work_dir")
    ap.add_argument("--release-tag", required=True)
    ap.add_argument("--jobs-root", default="jobs")
    ap.add_argument("--duration-seconds", type=int, default=None)
    ap.add_argument("--window-seconds", type=int, default=6)
    args = ap.parse_args()
    try:
        manifest = run_bundle(
            args.job_id, args.work_dir, args.release_tag,
            jobs_root=args.jobs_root,
            duration_seconds=args.duration_seconds,
            window_seconds=args.window_seconds,
        )
    except BundleError as exc:
        print(f"bundle error: {exc}", file=sys.stderr)
        raise SystemExit(2)
    print(json.dumps(manifest, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()


__all__ = [
    "BUNDLE_ASSETS", "BundleError", "sha256_file", "make_zip",
    "generate_prompt", "build_manifest", "run_bundle",
]
